entrada = input('digite algo: ')
print(type(entrada))
print('so tem espaços?', entrada.isspace())
print('é numero? ', entrada.isnumeric())
print('é alfabetico? ', entrada.isalpha())
print('é alfanumerico? ', entrada.isalnum())
print('está em maiúsculas? ', entrada.isupper())
print('está em minúsculas? ', entrada.islower())
print('está capitalizada? ', entrada.istitle())
